<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar</name>
   <tag></tag>
   <elementGuidId>02469fae-aa97-4689-aff0-a81a7b21a886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div/div/main/form/p[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b681de93-a175-478a-bd64-2f60eda5fafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Register</value>
      <webElementGuid>e6b5c490-68ea-4cb8-9634-a6a4c64503a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary-color hover:text-gray-400</value>
      <webElementGuid>8db76dc8-4a5a-4277-bb62-66aecd888843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Daftar
          </value>
      <webElementGuid>c935c273-0809-4da7-9fb5-d3c6e19c305f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;my-5 mx-auto lg:flex items-center mt-20&quot;]/div[@class=&quot;mx-10 flex md:justify-center lg:w-1/2 items-center&quot;]/div[@class=&quot;xm-auto w-full&quot;]/main[1]/form[@class=&quot;grid gap-4&quot;]/p[@class=&quot;text-center text-xs&quot;]/a[@class=&quot;text-primary-color hover:text-gray-400&quot;]</value>
      <webElementGuid>5f6f78ab-d665-4484-af7a-6dcb1aa6f515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/main/form/p[3]/a</value>
      <webElementGuid>70115a0b-c0bb-4fd0-8e80-0fe2fde83b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar')]</value>
      <webElementGuid>aa5a8abe-c682-4599-9865-70e8bb0c83f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::a[1]</value>
      <webElementGuid>aefb90c5-b393-4aea-8cbe-2b705a24206f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi?'])[1]/following::a[1]</value>
      <webElementGuid>7fa2bad7-7fbc-435b-8579-23da06ec6324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>c0fd04cc-5071-4911-a1ee-3ea99ed1fab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Register')]</value>
      <webElementGuid>c3b24164-ccd5-4db0-a84a-63555b82cce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/a</value>
      <webElementGuid>5f8a57a8-707f-4349-8d4e-d45799a4d4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Register' and (text() = '
            Daftar
          ' or . = '
            Daftar
          ')]</value>
      <webElementGuid>5e3a709a-cbdf-4139-94c5-3d2731f53b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
