<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Konsultasi</name>
   <tag></tag>
   <elementGuidId>44783e99-7432-45dd-a5ab-2e01a6cd3100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ca397fd-fd8b-4af6-9085-f3dabe8e8910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultation</value>
      <webElementGuid>faf579ca-8463-4cd9-90f3-944ff06b1314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Konsultasi
      </value>
      <webElementGuid>4acf5331-b767-4db3-a17b-4c8da9b1c39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;flex flex-col h-screen justify-between&quot;]/header[1]/div[@class=&quot;lg:flex justify-between sticky -bottom-0 px-16 py-3 text-gray-older bg-white items-center hidden&quot;]/div[@class=&quot;flex gap-16&quot;]/div[@class=&quot;flex gap-14 font-medium items-center&quot;]/a[2]</value>
      <webElementGuid>91cd0ed3-33ac-47b4-81ca-3e443519a0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div/div/div[2]/a[2]</value>
      <webElementGuid>0aa5f47a-97a5-455e-a0f6-4bac9a913024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Konsultasi')]</value>
      <webElementGuid>2989be52-9e3c-469f-a060-3d93cbc974aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[1]</value>
      <webElementGuid>4737eb1e-c673-4aa6-9aa0-4aa5be8b6df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gompu'])[2]/following::a[2]</value>
      <webElementGuid>5c9250c5-bf66-4bae-896e-73fe7fa93e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[1]</value>
      <webElementGuid>9c6fa91c-903e-41fe-89d2-ed792ec79510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk Semua Pelajar, Konsultasi dan Acara Harian'])[1]/preceding::a[2]</value>
      <webElementGuid>f186ea44-617f-4af0-ad43-00bf43e63d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konsultasi']/parent::*</value>
      <webElementGuid>fd11752c-c274-4536-a6fa-2255abc1d814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/consultation')]</value>
      <webElementGuid>05257b7b-75be-4bfc-803d-f2e4bccc9db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>5ef3013a-3350-42a8-8ded-4e2681269bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/consultation' and (text() = '
        Konsultasi
      ' or . = '
        Konsultasi
      ')]</value>
      <webElementGuid>7e973395-8ab3-4525-a6fb-cbcef74c268d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
