<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>86fa53ba-3cf1-4d21-b814-c8b655db12c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.font-medium.px-8.py-2.text-white.bg-new-yellow.rounded-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>817ac3b9-1f8a-49a3-b1f4-82cb20788407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>ddb1817f-f8d6-4c03-a86a-76dc0e34be16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium px-8 py-2 text-white bg-new-yellow rounded-lg</value>
      <webElementGuid>939a1ca1-9be7-422f-a3c1-f85978f697ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Login
    </value>
      <webElementGuid>977b11e8-0ac2-4a55-b8d9-0f603bd089da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;flex flex-col h-screen justify-between&quot;]/header[1]/div[@class=&quot;lg:flex justify-between sticky -bottom-0 px-16 py-3 text-gray-older bg-white items-center hidden&quot;]/div[@class=&quot;flex gap-2&quot;]/a[@class=&quot;font-medium px-8 py-2 text-white bg-new-yellow rounded-lg&quot;]</value>
      <webElementGuid>0eff1cd3-74cd-4588-8b7a-8aeefefd6c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div/div[2]/a</value>
      <webElementGuid>5de63ef9-6b60-482a-b2ec-d57a619db2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>e5b2f6c8-316a-4036-96e7-87c785c81ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konsultasi'])[1]/following::a[1]</value>
      <webElementGuid>fcc92e71-0933-4368-b510-60b49a845e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[2]</value>
      <webElementGuid>f837b229-e043-4fe9-b7ae-46d792141bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk Semua Pelajar, Konsultasi dan Acara Harian'])[1]/preceding::a[1]</value>
      <webElementGuid>b0e6eafb-e3c3-4637-b20c-ab00402669c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo GompuPoin'])[1]/preceding::a[1]</value>
      <webElementGuid>cfc99af8-3ef9-4f0b-a40a-68b185938956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>a6118526-e6d4-4c5d-9dcf-bf501d3aa8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login')]</value>
      <webElementGuid>8709af07-04b1-4212-be40-362c0e76dc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>16a9ca7b-0a46-43a0-a930-49dba1d9ccae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login' and (text() = '
      Login
    ' or . = '
      Login
    ')]</value>
      <webElementGuid>36f3a6aa-a5f5-4088-a65c-eaea0cd8db80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
