<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Registrasi</name>
   <tag></tag>
   <elementGuidId>1ce9661a-b4e5-4a19-a4dc-b2e6716454be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a16b6465-3a15-456c-9987-abad871adf3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>04be8518-f751-43a1-8d65-514c48c76015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary mt-8 w-full md:text-2xl disabled:bg-gray-300 disabled:text-black</value>
      <webElementGuid>04e324d3-d72e-432f-bbcc-8acfedadfd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Registrasi
        </value>
      <webElementGuid>33babd89-583d-4c0f-aa54-ff47222fd753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;pt-5 pb-12 lg:flex mt-20&quot;]/div[@class=&quot;mx-10 flex md:justify-center lg:w-1/2 items-center&quot;]/div[@class=&quot;xm-auto w-full&quot;]/main[1]/form[@class=&quot;grid gap-4&quot;]/button[@class=&quot;btn-primary mt-8 w-full md:text-2xl disabled:bg-gray-300 disabled:text-black&quot;]</value>
      <webElementGuid>1570892d-218a-40b4-82ab-2c0bb2c7f1e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>f26dea54-441f-43d3-9d04-be808c66c621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/main/form/button</value>
      <webElementGuid>3efd4413-2dc8-492f-89cc-51e2f2c7cddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/following::button[2]</value>
      <webElementGuid>2dffde6c-c63c-435a-a05e-2cfd1e5e3ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Email'])[1]/following::button[2]</value>
      <webElementGuid>e22628d9-f905-428d-97d8-9bc755879e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::button[1]</value>
      <webElementGuid>3f072cb5-42c6-4d0b-990f-c9459c066769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>71f81e4c-5283-4b62-894a-8eaab9b2905e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
          Registrasi
        ' or . = '
          Registrasi
        ')]</value>
      <webElementGuid>a2dcb14d-01cd-4217-85c9-62e5116e6a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
