<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login_m-4</name>
   <tag></tag>
   <elementGuidId>3740496e-a994-497d-bc99-8fc8358e6578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div/main/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.m-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5bb50356-092c-4101-b33b-d6b8e6aa03c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/back.b4ca446.svg</value>
      <webElementGuid>0e052957-175b-47ee-b0ef-6d2fa91356fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>b6c55a80-bca5-45af-8da2-e6b88eb5e3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-4</value>
      <webElementGuid>92e5851b-361c-4b48-9706-6a6f822278d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[1]/div[@class=&quot;flex flex-col justify-between&quot;]/main[@class=&quot;lg:px-16&quot;]/div[@class=&quot;flex gap-3 items-center&quot;]/a[@class=&quot;nuxt-link-active&quot;]/img[@class=&quot;m-4&quot;]</value>
      <webElementGuid>867edae4-4b57-4664-83aa-f24f26791718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/main/div/a/img</value>
      <webElementGuid>8ca82cc9-90ac-47ab-9948-8cbb47920d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Back']</value>
      <webElementGuid>6f090430-0b60-4cf4-a98c-3b7e282559e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>72ca6135-4e0c-4e11-a6b2-a405767836e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_nuxt/img/back.b4ca446.svg' and @alt = 'Back']</value>
      <webElementGuid>feff2101-ba49-43d5-9cac-f7c66934a084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
