<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>3219fa19-2668-4301-94f1-6314e1f4e198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.font-medium.px-8.py-2.text-white.bg-new-yellow.rounded-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe6b041e-e36d-4bb0-8d54-30ae91a3dfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>e69e85f2-225f-4394-bcfd-e9df4b141ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium px-8 py-2 text-white bg-new-yellow rounded-lg</value>
      <webElementGuid>778640e8-112c-4436-a16c-184f77c0fbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Login
    </value>
      <webElementGuid>48f7a8b9-b362-4baa-8917-d5b275d5dd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;flex flex-col h-screen justify-between&quot;]/header[1]/div[@class=&quot;lg:flex justify-between sticky -bottom-0 px-16 py-3 text-gray-older bg-white items-center hidden&quot;]/div[@class=&quot;flex gap-2&quot;]/a[@class=&quot;font-medium px-8 py-2 text-white bg-new-yellow rounded-lg&quot;]</value>
      <webElementGuid>2e351bcb-95b1-4091-b26d-e387a1974e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div/div[2]/a</value>
      <webElementGuid>1d06d478-4800-4316-9d33-dc32d19c9b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>4b36e39c-4fb5-49e8-923b-8114452b6810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konsultasi'])[1]/following::a[1]</value>
      <webElementGuid>88b4e695-354e-4756-b323-77749e0ab3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[2]</value>
      <webElementGuid>eaec905c-64a2-4c55-9e29-21449a1ac120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk Semua Pelajar, Konsultasi dan Acara Harian'])[1]/preceding::a[1]</value>
      <webElementGuid>0da62ec8-feaf-4f26-9c02-3ea88e2b7334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo GompuPoin'])[1]/preceding::a[1]</value>
      <webElementGuid>86a1ecc1-3e3e-4708-a197-52c1c7ccdc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>b755e3a0-52b0-4c0c-8d12-1dc7e1bd3a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login')]</value>
      <webElementGuid>45b21118-a829-40e9-ba01-3e70bf8425c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>f92dde59-5ef1-4f08-ad62-1848fdf74d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login' and (text() = '
      Login
    ' or . = '
      Login
    ')]</value>
      <webElementGuid>3c225356-9d12-4f95-9772-efbee38c0dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
