<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profil</name>
   <tag></tag>
   <elementGuidId>9b6d0b12-55be-409f-960a-3dabf9284d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div/div/div[2]/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bec1bd30-47bf-40f7-8258-8eea225b272c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/profile</value>
      <webElementGuid>376a2888-a9ca-4387-bbf4-294f4bf12ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Profil
      </value>
      <webElementGuid>f900f68a-6ab0-45cb-91ca-4f0c6a878d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;flex flex-col h-screen justify-between&quot;]/header[1]/div[@class=&quot;lg:flex justify-between sticky -bottom-0 px-16 py-3 text-gray-older bg-white items-center hidden&quot;]/div[@class=&quot;flex gap-16&quot;]/div[@class=&quot;flex gap-14 font-medium items-center&quot;]/a[4]</value>
      <webElementGuid>942287f1-dc3e-4404-a0dd-f1c0091a63ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div/div/div[2]/a[4]</value>
      <webElementGuid>5707bb81-2205-41a9-ac55-29ef017abbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Profil')]</value>
      <webElementGuid>bc1af379-52e8-4048-b0ab-499fcd42bb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktifitas'])[1]/following::a[1]</value>
      <webElementGuid>5c5d11b8-c6a9-4b5f-8797-3d2c0f7bc8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konsultasi'])[1]/following::a[2]</value>
      <webElementGuid>3f9d90f3-b1a1-4ead-89aa-1f3b8812abf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk Semua Pelajar, Konsultasi dan Acara Harian'])[1]/preceding::a[1]</value>
      <webElementGuid>db5af169-8dd9-4b35-a031-6cd27d516f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo GompuPoin'])[1]/preceding::a[1]</value>
      <webElementGuid>8181e84e-1549-4be8-8c19-a411388ec935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profil']/parent::*</value>
      <webElementGuid>94647c65-6aa3-467e-9049-7f99c3445bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/profile')]</value>
      <webElementGuid>777bd1b1-786b-4060-b208-98019ebc88b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>3da92242-d2b8-49a7-aa87-c1e87d128a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/profile' and (text() = '
        Profil
      ' or . = '
        Profil
      ')]</value>
      <webElementGuid>4ecd345d-9258-48d4-9db4-2dc6f02c7111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
