<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fotoProfile</name>
   <tag></tag>
   <elementGuidId>bdefc109-e137-4579-ab7c-938d86e819ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c93e1e05-6d91-4843-8ac2-2eec511ab9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>b8aa0bd1-b4e7-4932-9eac-f4fdbd69b68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>903d2fca-5e9b-4a9a-b87d-43d19e14e760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>1c9b6c55-6c70-497e-b590-e399b50557e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pt-4 w-56</value>
      <webElementGuid>cd8a2375-a99b-4b63-a9f5-c643a1bd16df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;pb-7text-gray-older&quot;]/div[@class=&quot;bg-new-yellow rounded-b-xl&quot;]/div[1]/div[@class=&quot;rounded-b-[60px] py-4 lg:px-16 text-center text-white&quot;]/input[@class=&quot;pt-4 w-56&quot;]</value>
      <webElementGuid>9f416618-6dc0-4691-b19b-857c66e678f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='img']</value>
      <webElementGuid>25906fd3-e590-4030-b397-a0f8297aab9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div[2]/input</value>
      <webElementGuid>cd511a17-f8c3-4924-a8c4-024ef00a6990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>63d0a456-4294-486a-a2df-e807980c6220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'img']</value>
      <webElementGuid>0f43bf0c-732a-4418-9496-2277ae291f52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
