<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Full name cant be blank</name>
   <tag></tag>
   <elementGuidId>cbb98019-074a-419c-9fc3-4c26a42b8ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='swal2-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swal2-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b5ebb81c-d6f1-4c29-829c-9a4f637e1657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>8ab8b7cd-1987-495f-8f74-0599117bae83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>26d3fc21-02bc-4552-8dfa-29485bdd3954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full name can't be blank</value>
      <webElementGuid>dd52e19c-3858-4081-ab60-06105db34785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-title&quot;)</value>
      <webElementGuid>f342bda5-f3ae-4326-8422-a24f4318b867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='swal2-title']</value>
      <webElementGuid>99847bb7-3e49-4f1e-a605-85706dbd274c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'swal2-title', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>8a68955d-40c9-4b04-8bef-458900ea2f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h2[1]</value>
      <webElementGuid>3ae05e6c-427f-4337-af0e-509f73602757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::h2[1]</value>
      <webElementGuid>bd083396-e8a5-406e-9bdb-baf1a714ab53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::h2[1]</value>
      <webElementGuid>7f3a9ef2-77c4-4d9b-9ae2-0e680ce34299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h2</value>
      <webElementGuid>b041f1e6-55e1-4990-ba93-47f4881f3e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'swal2-title' and (text() = concat(&quot;Full name can&quot; , &quot;'&quot; , &quot;t be blank&quot;) or . = concat(&quot;Full name can&quot; , &quot;'&quot; , &quot;t be blank&quot;))]</value>
      <webElementGuid>17c44e71-5de6-4ec1-b1fe-df0ef91d19c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
