<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Profile_img</name>
   <tag></tag>
   <elementGuidId>5fc5810d-bca1-43cd-9de1-7b202bd855ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;img&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c79a27d5-0bbb-4e7f-936c-7345d70b0b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>86f7855e-ce47-434f-91e0-f8bccc2b3ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b12e27a-c988-47ff-9264-c2cca55b473f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>e9213a76-708d-4e8f-8ac4-3ee68a9020ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pt-4 w-56</value>
      <webElementGuid>091ec8d0-efe5-4f70-b6fa-68d86aabc171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;pb-7text-gray-older&quot;]/div[@class=&quot;bg-new-yellow rounded-b-xl&quot;]/div[1]/div[@class=&quot;rounded-b-[60px] py-4 lg:px-16 text-center text-white&quot;]/input[@class=&quot;pt-4 w-56&quot;]</value>
      <webElementGuid>46c3af90-a669-47a1-8822-d34a2b09e5a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='img']</value>
      <webElementGuid>6a1704de-c452-4c5a-9712-0dd5d9bf93f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div[2]/input</value>
      <webElementGuid>d8ab2187-3bfc-4a29-95b0-116476f27661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4b896a3b-ada2-4701-94b0-856890b1bdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'img']</value>
      <webElementGuid>d0388c97-b7dc-46b8-9c29-38ce763adce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
