<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_noHandphone</name>
   <tag></tag>
   <elementGuidId>50090d49-45ac-4561-8d8b-a6d7276c6538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.w-full.h-full.ml-2.border-l-2.py-3.pl-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe699ef-457c-40fd-a976-8d6be7015195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6ffdc533-5665-4b4e-8e6e-d49804db06cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0081366321353</value>
      <webElementGuid>3bc3d2d4-1d9c-4964-bc54-1c9a260aca79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-full ml-2 border-l-2 py-3 pl-1</value>
      <webElementGuid>0532fee2-9831-4f4d-ab43-ea15c58990b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;pb-7text-gray-older&quot;]/form[@class=&quot;px-5 pt-2&quot;]/div[@class=&quot;flex items-center border-2 rounded-md mt-3 mb-8&quot;]/input[@class=&quot;w-full h-full ml-2 border-l-2 py-3 pl-1&quot;]</value>
      <webElementGuid>983c10a0-9994-4f30-80b6-ae00463b23b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>1f7f3ed6-77f9-471b-b291-e446772e0793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/form/div/input</value>
      <webElementGuid>9f4bf17e-35e7-43a1-8f73-cc51b519f6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>0a1c6951-9116-4307-950d-30ec3725850c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '0081366321353']</value>
      <webElementGuid>e9d1909a-46a6-468e-bb64-8dacfd8b5970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
