<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputImage</name>
   <tag></tag>
   <elementGuidId>d1886ee5-069f-4d6f-b997-d20f6f1c2f2c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;img&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>169c313e-12aa-4e72-b82c-c144560303c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>c05eee39-6ada-4f88-8a7f-e7138ce0f916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7dd39836-d95b-4294-b43a-6f4d802c70e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>dc5fa637-ce4c-4654-83cd-1c554bde4613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pt-4 w-56</value>
      <webElementGuid>ce4387a8-e0d0-43e1-8f7e-d4d2fcf82394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-white my-0 mx-auto&quot;]/div[@class=&quot;pb-7text-gray-older&quot;]/div[@class=&quot;bg-new-yellow rounded-b-xl&quot;]/div[1]/div[@class=&quot;rounded-b-[60px] py-4 lg:px-16 text-center text-white&quot;]/input[@class=&quot;pt-4 w-56&quot;]</value>
      <webElementGuid>01456568-c8ca-4f21-ba68-06531d985cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='img']</value>
      <webElementGuid>8d576472-0df1-4dfd-bff2-a3540d83401c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div[2]/input</value>
      <webElementGuid>1e31fdaf-98f6-45e5-81a5-407e1fd03d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>46304728-0456-41e5-a5cf-56f5adb8fbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'img']</value>
      <webElementGuid>61b2f5e2-9fa7-40fb-af14-bcddb5473529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
